### ISSUE TITLE
 Issue with Foreign Keys in SQL Table Creation

### ISSUE THREAD

**Issue by sithu-go** [cookieY/Yearning#1172]
Please provide titles that are straightforward and concise. exp: [Question] How to use or [Feature] Add new feature

      请提供简单明了的标题。例如 [Question] 如何使用 or [Feature] 添加新功能

**Comment by sithu-go** [comment]
@dosu. 
There's no DDLEnableForeignKey. I only see DDLEnablePrimaryKey.


![image](https://github.com/user-attachments/assets/19bd6ab9-fe9d-43fd-973e-d2a6c1705cd8)

**Comment by sithu-go** [comment]
I'm not a developer from yearning. How to set AuditRole in that struct.

I just use this app. 
@dosu

**Comment by sithu-go** [comment]
You just edited my issue detail. Everything includes in there.

Overwriting user issue's description is not a good idea.
@dosu

sorry to mention you here. I think you should check this bot.
@cookieY

**Comment by sithu-go** [comment]
I'm using 

docker 
`
        image:  yeelabs/yearning:latest

`

does this docker version include DDLEnableForeignKey?

@dosu

**Comment by sithu-go** [comment]
that is how my docker compose file looks  like.

```yml
services:
    yearning:
        image: yeelabs/yearning:latest
        environment:
           MYSQL_USER: yearning
           MYSQL_PASSWORD: password
           MYSQL_ADDR: mysql
           MYSQL_DB: yearning
           SECRET_KEY: secretKey
           IS_DOCKER: is_docker
           Y_LANG: en_US
        ports:
           - 8000:8000
        # 首次使用请先初始化
        command: /bin/bash -c "./Yearning install && ./Yearning run"
        depends_on:
           - mysql
        restart: always

    mysql:
        image: mysql:5.7
        environment:
           MYSQL_ROOT_PASSWORD: password
           MYSQL_DATABASE: yearning
           MYSQL_USER: yearning
           MYSQL_PASSWORD: password
        command:
           - --character-set-server=utf8mb4
           - --collation-server=utf8mb4_general_ci
        volumes:
           - ./data/mysql:/var/lib/mysql

```

In docker hub, yeelabs/yearning is updated 3 months ago.

Isit a problem?

**Comment by sithu-go** [comment]
@dosu

that is how my docker compose file looks  like.

```yml
services:
    yearning:
        image: yeelabs/yearning:latest
        environment:
           MYSQL_USER: yearning
           MYSQL_PASSWORD: password
           MYSQL_ADDR: mysql
           MYSQL_DB: yearning
           SECRET_KEY: secretKey
           IS_DOCKER: is_docker
           Y_LANG: en_US
        ports:
           - 8000:8000
        # 首次使用请先初始化
        command: /bin/bash -c "./Yearning install && ./Yearning run"
        depends_on:
           - mysql
        restart: always

    mysql:
        image: mysql:5.7
        environment:
           MYSQL_ROOT_PASSWORD: password
           MYSQL_DATABASE: yearning
           MYSQL_USER: yearning
           MYSQL_PASSWORD: password
        command:
           - --character-set-server=utf8mb4
           - --collation-server=utf8mb4_general_ci
        volumes:
           - ./data/mysql:/var/lib/mysql

```

In docker hub, yeelabs/yearning is updated 3 months ago.

Isit a problem?
