### ISSUE TITLE
更新 Dockerfile 及 增加 docker-compose

### ISSUE THREAD

**Issue by tangx** [cookieY/Yearning#201]
## Dockerfile

dockerfile 中还在使用  3.3 的源，有点问题。

```Dockerfile
FROM alpine:latest

LABEL maintainer="HenryYee-2019/08/13"

EXPOSE 8000

COPY Yearning  /opt/Yearning
COPY dist /opt/dist
COPY conf.toml /opt/conf.toml

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" >> /etc/timezone
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

WORKDIR /opt

ENTRYPOINT  ["/opt/Yearning"]

CMD ["-m", "-s"]
```

## docker-compose

希望在压缩包中增加docker-compose, 可以更快速的体验内容

```yaml
version: '3'

services:
  yearning:
    image: test/yearning:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: yearning
      MYSQL_PASSWORD: ukC2ZkcG_ZTeb
      MYSQL_ADDR: mysql
      MYSQL_DB: yearning
    ports:
      - 8000:8000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
      MYSQL_DATABASE: yearning
      MYSQL_USER: yearning
      MYSQL_PASSWORD: ukC2ZkcG_ZTeb

```
