### ISSUE TITLE
udpate docker-compose.yml: add character

### ISSUE THREAD

**Issue by tangx** [cookieY/Yearning#224]
`docker-compose.yml`

```yaml
version: '3'

services:
  yearning:
    depends_on:
      - mysql
    image: test/yearning:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: yearning
      MYSQL_PASSWORD: ukC2ZkcG_ZTeb
      MYSQL_ADDR: mysql
      MYSQL_DB: yearning
    ports:
      - 8000:8000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
      MYSQL_DATABASE: yearning
      MYSQL_USER: yearning
      MYSQL_PASSWORD: ukC2ZkcG_ZTeb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
```
