### ISSUE TITLE
docker-compose 部署一直报错

### ISSUE THREAD

**Issue by xxdyu** [cookieY/Yearning#599]
**Describe** **描述**
```
  version: '3'
  services:
      yearning:
          image: chaiyd/yearning:v3.0.1
          environment:
             MYSQL_USER: yearning
             MYSQL_PASSWORD: "ukC2ZkcG_ZTeb"
             MYSQL_ADDR: mysql
             MYSQL_DB: yearning
          ports:
             - 8000:8000
          command: /bin/bash -c "./Yearning install"
        #   volumes:
        #      - D:\phpstudy_pro\WWW\sql-check-go\docker\conf.toml:/opt/conf.toml
          depends_on:
             - mysql
          restart: always

    mysql:
        image: bitnami/mysql:5.7.38
        environment:
           MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_DATABASE: yearning
           MYSQL_USER: yearning
           MYSQL_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_CHARACTER_SET: utf8mb4
           MYSQL_COLLATE: utf8mb4_general_ci

```

**To Reproduce** **如何复现**
docker-compose up 报错

**Expected behavior** **期望的结果**
正常部署

**Screenshots** **截图**
![image](https://user-images.githubusercontent.com/32918557/175198846-14dd5484-6e30-4f6d-b890-8ab44bafb7ce.png)

**Desktop (please complete the following information):** **环境**

**Additional context** **其他**

**Comment by chaiyd** [comment]
- 报错为数据库原因
- mysql 镜像是二次封装的，这里没有办法判断是否支持下列环境变量
 ```
        environment:
           MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_DATABASE: yearning
           MYSQL_USER: yearning
           MYSQL_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_CHARACTER_SET: utf8mb4
           MYSQL_COLLATE: utf8mb4_general_ci
```

**Comment by xxdyu** [comment]
我用 原始文件的MySQL5.7镜像也是或者报错 麻烦给看下

**Comment by chaiyd** [comment]
> 我用 原始文件的MySQL5.7镜像也是或者报错 麻烦给看下

- compose 文件呢，直接用的这个，还是有更改https://github.com/cookieY/Yearning/blob/next/docker/docker-compose.yml

```
version: '3'

services:
    yearning:
        image: chaiyd/yearning:latest
        environment:
           MYSQL_USER: yearning
           MYSQL_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_ADDR: mysql
           MYSQL_DB: yearning
        ports:
           - 8000:8000
        # 首次使用请先初始化
        #command: /bin/bash -c "./Yearning install"
        #volumes:
        #   - ./conf.toml:/opt/conf.toml
        depends_on:
           - mysql
        restart: always

    mysql:
        image: mysql:5.7
        environment:
           MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
           MYSQL_DATABASE: yearning
           MYSQL_USER: yearning
           MYSQL_PASSWORD: ukC2ZkcG_ZTeb
        command:
           - --character-set-server=utf8mb4
           - --collation-server=utf8mb4_general_ci
        volumes:
           - ./data/mysql:/var/lib/mysql

# 默认账号：admin，默认密码：Yearning_admin
```
